# Generated by Django 5.1.6 on 2025-05-28 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskSystem', '0005_alter_comment_options_alter_task_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('dislike', 'user'), ('like', 'user')},
        ),
    ]
